# 基础镜像：使用轻量级的 JDK 21
FROM eclipse-temurin:21-jre-alpine

# 设置工作目录
WORKDIR /app

# 把编译好的 jar 包拷进去
COPY target/*.jar app.jar

# 关键：设置 JVM 内存，2G 内存的服务器建议这样给：
ENTRYPOINT ["java", "-Xmx128m", "-Xms128m", "-jar", "app.jar"]