spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 1

server:
  compression:
    enabled: true

logging:
  level:
    root: INFO
    com.jiejie.gateway: INFO
