server:
  port: 8082

spring:
  application:
    name: product-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:8848
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yaml

mybatis:
  configuration:
    map-underscore-to-camel-case: true

file:
  upload-path: ${FILE_UPLOAD_PATH:/Users/jiejie/Desktop/web/my-system-cloud/pictures/}
